# Multiple Linear Regression
importing the libraries


In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import rand

df  = pd.DataFrame(rand( 50 , 3)*10, columns = 'Hours_studied Hours_slept iQ '.split())
df.head(2)

Hours_studied  Hours_slept        iQ
0       2.161059     7.918699  5.462386
1       2.158807     0.722140  7.855455

In [3]:
from random import choice

location = []
for i in range(50):
    
    location.append(choice(["New Delhi" , "Pune" , "Bangalore"]))
 

df['Location'] = location

df.head()

Hours_studied  Hours_slept        iQ   Location
0       2.161059     7.918699  5.462386  New Delhi
1       2.158807     0.722140  7.855455  New Delhi
2       2.126487     0.586581  8.998022       Pune
3       0.527127     2.202517  9.443748  New Delhi
4       7.113369     1.058224  2.036905  Bangalore

In [4]:
df['Marks'] = (1.73 + (3.34*df['Hours_studied'])
                    + (2.45*df['Hours_slept'])
                    + (1.83*df['iQ']  ))
df['Marks'] =  df['Marks'] +np.random.rand(50)*20
               
df.to_csv('Students.csv',index=False)

In [5]:
df.head()

Hours_studied  Hours_slept        iQ   Location      Marks
0       2.161059     7.918699  5.462386  New Delhi  43.007101
1       2.158807     0.722140  7.855455  New Delhi  33.709174
2       2.126487     0.586581  8.998022       Pune  35.551047
3       0.527127     2.202517  9.443748  New Delhi  34.227671
4       7.113369     1.058224  2.036905  Bangalore  43.232248

# Importing the dataset


In [6]:
dataset = pd.read_csv('Students.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[2.161058784766259 7.918698547228173 5.462385633638075 'New Delhi']
 [2.158807388664025 0.7221399225381375 7.855455209448716 'New Delhi']
 [2.1264870502255957 0.5865806923876571 8.998021789917015 'Pune']
 [0.5271267776251687 2.2025167140403914 9.443748027419748 'New Delhi']
 [7.113368581267504 1.0582243289766249 2.0369054122351877 'Bangalore']
 [6.940097418083119 4.600861683299918 1.9961935391633967 'Pune']
 [7.814017905961002 8.52965812205327 9.705109154835482 'Pune']
 [1.6754380849979431 3.462071812828068 7.14454749860522 'New Delhi']
 [4.883797719250627 8.731913289209986 9.284375518909878 'New Delhi']
 [9.50243876574088 7.190438863289935 3.04014990582977 'Pune']
 [5.372371059533836 9.146591263877369 0.3798372770208535 'Bangalore']
 [5.016270516137874 2.3832923277039098 7.67747506876416 'New Delhi']
 [2.445017076555347 7.33616424011686 9.725084334411092 'New Delhi']
 [5.806738370795172 7.536132773937631 7.60896257796413 'Bangalore']
 [0.3420210980365001 3.6008140679833445 0.29563527

In [7]:
print(y)

[43.00710125 33.70917424 35.55104683 34.22767125 43.23224794 42.51718031
 69.00281482 42.26771503 56.5390444  64.05743303 57.26412675 50.37369746
 63.67004161 64.50380906 17.33579665 51.32414879 52.84120128 67.65734419
 57.60430783 65.23070231 61.64137575 44.80041472 47.875295   57.50411153
 54.46408541 38.534402   56.9282326  61.71396973 31.62460953 44.31192743
 38.99942172 32.02322113 35.21158446 39.06026572 44.82027553 35.60377826
 61.80859722 43.57615894 44.41058543 37.5668897  42.70089673 25.94958165
 57.63981076 72.2697406  53.83966974 42.24676461 44.63390997 33.80622701
 49.4313147  26.71716726]


# Encoding the categorical data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')
print(ct)

X = np.array(ct.fit_transform(X))

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3])])


In [9]:
print(X)

[[0.0 1.0 0.0 2.161058784766259 7.918698547228173 5.462385633638075]
 [0.0 1.0 0.0 2.158807388664025 0.7221399225381375 7.855455209448716]
 [0.0 0.0 1.0 2.1264870502255957 0.5865806923876571 8.998021789917015]
 [0.0 1.0 0.0 0.5271267776251687 2.2025167140403914 9.443748027419748]
 [1.0 0.0 0.0 7.113368581267504 1.0582243289766249 2.0369054122351877]
 [0.0 0.0 1.0 6.940097418083119 4.600861683299918 1.9961935391633967]
 [0.0 0.0 1.0 7.814017905961002 8.52965812205327 9.705109154835482]
 [0.0 1.0 0.0 1.6754380849979431 3.462071812828068 7.14454749860522]
 [0.0 1.0 0.0 4.883797719250627 8.731913289209986 9.284375518909878]
 [0.0 0.0 1.0 9.50243876574088 7.190438863289935 3.04014990582977]
 [1.0 0.0 0.0 5.372371059533836 9.146591263877369 0.3798372770208535]
 [0.0 1.0 0.0 5.016270516137874 2.3832923277039098 7.67747506876416]
 [0.0 1.0 0.0 2.445017076555347 7.33616424011686 9.725084334411092]
 [1.0 0.0 0.0 5.806738370795172 7.536132773937631 7.60896257796413]
 [1.0 0.0 0.0 0.34202109803650

# Splitting the  dataset into the training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
y_test

array([31.62460953, 50.37369746, 57.26412675, 25.94958165, 35.55104683,
       61.71396973, 44.41058543, 32.02322113, 47.875295  , 43.23224794])

# Training the multiple linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

# Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)
print("\n\n\nPredicted  Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))




Predicted  Actual
[[29.67 31.62]
 [48.41 50.37]
 [48.75 57.26]
 [28.37 25.95]
 [34.05 35.55]
 [53.17 61.71]
 [36.87 44.41]
 [30.21 32.02]
 [42.26 47.88]
 [40.01 43.23]]


In [14]:
np.set_printoptions(precision=2)
print(np.concatenate((X_test ,y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)),1)) 

[[0.0 0.0 1.0 0.5007821416192437 3.947270537698331 5.773424494810188
  29.669239044233198 31.624609527076416]
 [0.0 1.0 0.0 5.016270516137874 2.3832923277039098 7.67747506876416
  48.408254019010776 50.37369745596678]
 [1.0 0.0 0.0 5.372371059533836 9.146591263877369 0.3798372770208535
  48.74802721037123 57.26412675018624]
 [1.0 0.0 0.0 0.8416219903359334 3.8786739573900064 4.001599299531468
  28.365372300913187 25.949581646169467]
 [0.0 0.0 1.0 2.1264870502255957 0.5865806923876571 8.998021789917015
  34.04903815611868 35.55104683405658]
 [1.0 0.0 0.0 9.547273209388 3.6773611371840618 1.4782379413073476
  53.16580184261489 61.71396972975572]
 [1.0 0.0 0.0 6.695045286387915 0.127315864452443 2.22800878246074
  36.86545374789258 44.41058543240307]
 [0.0 0.0 1.0 4.087072012054169 1.2847287888677283 2.686424421651669
  30.21237636978669 32.02322113099186]
 [1.0 0.0 0.0 2.5907793723836314 5.95481644533272 5.678677096628382
  42.257220720928466 47.87529499604547]
 [1.0 0.0 0.0 7.1133685812

In [15]:
len(y_pred)

10

In [17]:
y_test

array([31.62, 50.37, 57.26, 25.95, 35.55, 61.71, 44.41, 32.02, 47.88,
       43.23])

In [18]:
y_pred

array([29.67, 48.41, 48.75, 28.37, 34.05, 53.17, 36.87, 30.21, 42.26,
       40.01])